### ISSUE TITLE
Request option to set detector config defaults in EDD Calibration

### ISSUE THREAD

**Issue by arwoll** [CHESSComputing/ChessAnalysisPipeline#107]
The new / recommended workflow for EDD detector calibration calls for an Energy calibration step followed by a tth calibration. Currently, the output file from Energy calibration includes defaults for, e.g., tth_initial_guess, which in general will be among the first things the user will want to specity. 

The current Energy config file reader permits these defaults to be set only at the per-detector level, as in the snippet below.

```
pipeline:
  # Perform energy calibration first
  - edd.MCAEnergyCalibrationProcessor:
      # Ce lines: Ka2=34.28, Ka1=34.72, Kb1=39.257, Kb2=40.236
      peak_energies: [34.72, 34.28,  39.257, 40.236]
      max_peak_index: 0
      fit_index_ranges: [[650, 850]]
      config:
        spec_file: raw_data/edd23-char-1/spec.log
        scan_number: 87
        scan_step_index: 40
        flux_file: reduced_data/analysis_ARW/flux.dft
        detectors:
          - detector_name: 0
            tth_initial_guess: 7.105
            include_energy_ranges: [[50, 100]]
            tth_max: 10.0
          - detector_name: 2
            tth_initial_guess: 7.105
            include_energy_ranges: [[50, 100]]
            tth_max: 10.0
...
```

**Propose:** permit specification of defaults for all detectors. For instance any item in the "detectors" section that is NOT "detector_name" could be interepreted as a default for all detectors, UNLESS overwitten in the detector specific location, e.g.:

```
pipeline:
  # Perform energy calibration first
  - edd.MCAEnergyCalibrationProcessor:
      # Ce lines: Ka2=34.28, Ka1=34.72, Kb1=39.257, Kb2=40.236
      peak_energies: [34.72, 34.28,  39.257, 40.236]
      max_peak_index: 0
      fit_index_ranges: [[650, 850]]
      config:
        spec_file: raw_data/edd23-char-1/spec.log
        scan_number: 87
        scan_step_index: 40
        flux_file: reduced_data/analysis_ARW/flux.dft
        detectors:
          - tth_initial_guess: 7.105
          - include_energy_ranges: [[50, 100]]
          - tth_max: 10.0
          - detector_name: 0             # <----  detector "0" uses all three defaults above
          - detector_name: 2             # <---- detector "2" uses the defaults for tth_initial_guess and tth_max, but overrides the energy range, e.g. due to some errant peak in that particular case
            include_energy_ranges: [[50, 90]]
...
```
