### ISSUE TITLE
EDD Energy / tth calibration option to specify & combine more than one scan point for better statistics

### ISSUE THREAD

**Issue by arwoll** [CHESSComputing/ChessAnalysisPipeline#108]
In the current EDD calibration workflow, the option exists to calibrate using a specific point of a scan, e.g as follows:

```
pipeline:
  # Perform energy calibration first
  - edd.MCAEnergyCalibrationProcessor:
      # Ce lines: Ka2=34.28, Ka1=34.72, Kb1=39.257, Kb2=40.236
      peak_energies: [34.72, 34.28,  39.257, 40.236]
      max_peak_index: 0
      fit_index_ranges: [[650, 850]]
      config:
        spec_file: raw_data/edd23-char-1/spec.log
        scan_number: 87
        scan_step_index: 40
        flux_file: reduced_data/analysis_ARW/flux.dft
        detectors:
          - detector_name: 0
            tth_initial_guess: 7.105
            include_energy_ranges: [[50, 100]]
            tth_max: 10.0
...
```

**Propose** change "scan_step_index" to "scan_step_indices" to allow the user to specify performing the calibration with a SUM of spectra from multiple points in scan, e.g.:

```
pipeline:
...
      config:
        spec_file: raw_data/edd23-char-1/spec.log
        scan_number: 87
        scan_step_indices: [38,39,40,41,42]
...
```

**Ot better yet, something functionally equivalent to**

```
pipeline:
...
      config:
        spec_file: raw_data/edd23-char-1/spec.log
        scan_number: 87
        scan_step_indices: list(range(30,51))
...
```

This would permit calibration with better statistics.
