### ISSUE TITLE
Add configuration pipeline item

### ISSUE THREAD

**Issue by vkuznet** [CHESSComputing/ChessAnalysisPipeline#63]
**Describe intended use of the requested PipelineItem**
To do proper integration with CHAPBook and allow portable configuration and location of pipieline workflows it will be useful to develop (with some defaults) a configuration module which will perform the following:
- setup CHAP ROOT location which will be used by CHAP tool and pipieline to load various workflows
- location of workflows area
- optionally define additional flags, like profile, etc.

Then, we can use such configuration pipeline module/item in every configuration, e.g.

```
# configuration
config:
  root: /path/workflows
  profile: true
  verbose_level: 1
  interactive_prompt: true
  input: /path/to/input/location
  output: /path/to/output/location

pipeline:
  # Collect map data
  - common.YAMLReader:
      filename: examples/saxswaxs/map_1d.yaml
      schema: MapConfig
```
In this example, the `root` defines main root area CHAP will use and all other pipeline files will use it, i.e. the `examples/saxswaxs/map_1d.yaml` will be defined not within current working directory but wrt to `root` path. The `profile` option will run profiler such that we do not need to specify this parameter at CLI, etc. We may have further extensions to configuration module, e.g. run interactive pipeline, or use verbosity level.

**Additional context**
Such configuration module will allow integration with CHAPBook service and/or relocation some parts of CHAP parts, e.g. examples, workflows, etc. to a different location.
